### ISSUE TITLE
Error on multiple choice

### ISSUE THREAD

**Issue by krulci** [nrkorte/McGraw-Bot#4]
![image](https://github.com/nrkorte/McGraw-Bot/assets/52474054/6aaa4988-c889-474c-ada3-b8cd3755ebac)

**Comment by krulci** [comment]
Below is the correct full xpath
```html
/html/body/awd-root/div[1]/awd-app-root/div/div[2]/div/awd-main-container/div/div/div/div[1]/awd-probe-navigation/div/div[1]/awd-probe/avalon-probe-renderer/div/div/aa-air-item/div/div/div/div/div/div/div/div/div/div[2]/fieldset/div[1]/div/mhe-radio-button/label/span/span/p
```

Below is the error xpath
```html
/html/body/awd-root/div[1]/awd-app-root/div/div[2]/div/awd-main-container/div/div/div/div[1]/awd-probe-navigation/div/div[1]/awd-probe/avalon-probe-renderer/div/aa-air-item/div/div/div/div/div/div/div/div/div/div[2]/fieldset/div[' + str(i + 1) + ']
```

**Comment by krulci** [comment]
So far I am seeing multiple choice, true or false, fill in the blank has a different xpath.
I did try except on them, but I am not sure about fill in the blank as the full xpath does not look similar to what you had.
Below is one of the full xpath of fill in the blank question that got hanged
```html
/html/body/awd-root/div[1]/awd-app-root/div/div[2]/div/awd-main-container/div/div/div/div[1]/awd-probe-navigation/div/div[1]/awd-probe/avalon-probe-renderer/div/div/aa-air-item/div/div/div/div/div/div/div/span/fieldset/div/p/span[1]/input
```

**Comment by nrkorte** [comment]
I don't have access to McGraw Hill anymore. At the time I made this, it was working on those XPaths. The T/F was intended to be dynamic, hence the [' + str(i + 1) + '] at the end. If you want, you can shoot me an email listed in the README and we can take a look at it together if you still have access to McGraw Hill and I will update main accordingly. Thanks for using this btw!

**Comment by krulci** [comment]
> I don't have access to McGraw Hill anymore. At the time I made this, it was working on those XPaths. The multiple choice was intended to be dynamic, hence the [' + str(i + 1) + '] at the end. If you want, you can shoot me an email or message on discord [listed in the README] and we can take a look at it together if you still have access to McGraw Hill and I will update main accordingly. Thanks for using this btw!

I have shoot you on discord
